config/routes.rb
require 'sidekiq/web'

Vncoding::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions"} do
    match '/' => 'sessions#new'
  end

  resources :encoding_jobs

  mount Sidekiq::Web => '/sidekiq'

end

app/models/encoding_job.rb
class EncodingJob
  include Mongoid::Document
  include Mongoid::Paperclip

  STATES = { 
    'inqueue'   => 0,
    'inprocess' => 1,
    'complete'  => 2,
    'error'     => 3
  }

  field :state, type: Integer, :default => 0
  field :callback_url
  field :video_url
  field :error
  field :format, :default => '.flv'
  field :s3_url
  field :encoded_video_path
  field :image_path

  has_mongoid_attached_file :video

  #OUT_DIR = '/home/rishi/work/vncoding/public/system'

  after_create {|doc| EncodingWorker.perform_async(doc.id.to_s) }
  
  def output_file_dir
    video.path.split(video_file_name).first
  end

  def output_file_name
    file_name = video_file_name.gsub(File.extname(video_file_name), '')
    out_dir = self.output_file_dir
    #"#{OUT_DIR}/#{file_name}#{format}"
    "#{out_dir}#{file_name}#{format}"
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/encoding_jobs_controller.rb
class EncodingJobsController < ApplicationController
  before_filter :authenticate_user!
  # GET /encoding_jobs
  # GET /encoding_jobs.json
  def index
    @encoding_jobs = EncodingJob.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @encoding_jobs }
    end
  end

  # GET /encoding_jobs/1
  # GET /encoding_jobs/1.json
  def show
    @encoding_job = EncodingJob.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @encoding_job }
    end
  end

  # GET /encoding_jobs/new
  # GET /encoding_jobs/new.json
  def new
    @encoding_job = EncodingJob.new
    
    respond_to do |format|
      format.html {}
      #format.html { render text: 'abbb', layout: false}
      format.json { render json: @encoding_job }
    end
  end

  # GET /encoding_jobs/1/edit
  def edit
    @encoding_job = EncodingJob.find(params[:id])
  end

  # POST /encoding_jobs
  # POST /encoding_jobs.json
  def create
    @encoding_job = EncodingJob.new(params[:encoding_job])

    respond_to do |format|
      if @encoding_job.save
        format.html { redirect_to @encoding_job, notice: 'Encoding job was successfully created.' }
        format.json { render json: @encoding_job, status: :created, location: @encoding_job }
      else
        format.html { render action: "new" }
        format.json { render json: @encoding_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /encoding_jobs/1
  # PUT /encoding_jobs/1.json
  def update
    @encoding_job = EncodingJob.find(params[:id])

    respond_to do |format|
      if @encoding_job.update_attributes(params[:encoding_job])
        format.html { redirect_to @encoding_job, notice: 'Encoding job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @encoding_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encoding_jobs/1
  # DELETE /encoding_jobs/1.json
  def destroy
    @encoding_job = EncodingJob.find(params[:id])
    @encoding_job.destroy

    respond_to do |format|
      format.html { redirect_to encoding_jobs_url }
      format.json { head :no_content }
    end
  end

  def status
    @encoding_job = EncodingJob.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    new_encoding_job_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encoding_jobs_helper.rb
module EncodingJobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/encoding_jobs/_form.html.haml
= form_for @encoding_job do |f|
  - if @encoding_job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@encoding_job.errors.count, "error")} prohibited this encoding_job from being saved:"
      %ul
        - @encoding_job.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :video
    = f.file_field :video
  .field
    = f.label :format
    = f.text_field :format
  .actions
    = f.submit 'Save'

app/views/encoding_jobs/edit.html.haml
%h1 Editing encoding_job

= render 'form'

= link_to 'Show', @encoding_job
\|
= link_to 'Back', encoding_jobs_path

app/views/encoding_jobs/index.html.haml
%h1 Listing encoding_jobs
%table
  %tr
    %th Video
    %th File Name

  - @encoding_jobs.each do |encoding_job|
    %tr
      //%td=# jw_player(encoding_job.encoded_video_path, { :width => 400, :height => 400, :screnshot => encoding_job.image_path})
      %td= jw_player(encoding_job.video.url, { :width => 400, :height => 400, :screnshot => encoding_job.image_path})
      %td= encoding_job.encoded_video_path
%br
%p
  S3 test
= jw_player('https://s3.amazonaws.com/other_testing/video.mp4', :width => 400, :height => 400)
= jw_player('https://s3.amazonaws.com/other_testing/ccd0d8bc2f6f667004c4124340a26922.mp4', :width => 400, :height => 400)
= link_to 'New Encoding job', new_encoding_job_path

app/views/encoding_jobs/new.html.haml
%h1 New encoding_job

= render 'form'

= link_to 'Back', encoding_jobs_path

app/views/encoding_jobs/show.html.haml
%p#notice= notice

= link_to 'Edit', edit_encoding_job_path(@encoding_job)

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title
      Encoder
    =stylesheet_link_tag    "application", :media => "all"
    =javascript_include_tag "application"
    =csrf_meta_tags
  %body{:style => "padding-top:60px;"}
    .navbar.navbar-inverse.navbar-fixed-top
      #navbar-inner.navbar-inner
        .container
          %a.brand{:href => "/"}
            Video Encoder
          .pull-right
            %ul.nav
              -if user_signed_in?   
                %li
                  = link_to current_user.email, edit_user_registration_path(current_user) 
                %li  
                  = link_to "Logout", destroy_user_session_path, :method => :delete
              -else
                %li
                  = link_to "Login", new_user_session_path
    .container          
      =yield